version: '2'
services:
  app:
    image: agonper/easyrent
    depends_on:
     - db
    volumes:
      - ./data/indexes:/var/lucene/indexes
      - ./data/easyrent:/var/easyrent
    ports:
      - "80:8080"
  db:
    image: postgres
    environment:
      POSTGRES_USER: easyrent
      POSTGRES_PASSWORD: easyrent
    volumes:
      - ./data/db:/var/lib/postgresql/data